// src/lib/productApiSlice.js
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

// Define your API service
export const productApi = createApi({
  reducerPath: 'productApi', // Name of the reducer
  baseQuery: fetchBaseQuery({ baseUrl: 'https://dummyjson.com/' }), // API base URL
  endpoints: (builder) => ({
    getProducts: builder.query({
      query: () => 'products?_limit=10', // API endpoint
    }),

    getProductById: builder.query({
      query: (id) => `products/${id}`, // Fetch a single product by ID
    }),
  }),
});

// Export hooks generated by the service
export const { useGetProductsQuery, useGetProductByIdQuery } = productApi;
